
# https://platform.openai.com/docs/pricing

# Existing 4o family (kept for compatibility if used elsewhere)
gpt-4o:
    input: 2.5       # $ per 1M tokens
    output: 10

gpt-4o-mini:
    input: 0.15
    output: 0.6

# 4.1 family
gpt-4.1:
    input: 2.00
    cached_input: 0.50
    output: 8.00

gpt-4.1-mini:
    input: 0.40
    cached_input: 0.10
    output: 1.60

gpt-4.1-nano:
    input: 0.10
    cached_input: 0.025
    output: 0.40

# 5 family
gpt-5:
    input: 1.25
    cached_input: 0.125
    output: 10.00

gpt-5-mini:
    input: 0.25
    cached_input: 0.025
    output: 2.00

gpt-5-nano:
    input: 0.05
    cached_input: 0.005
    output: 0.40

gpt-5-chat-latest:
    input: 1.25
    cached_input: 0.125
    output: 10.00

default:
    input: 0.15
    output: 0.6
